package com.erdong.warehouse.pojo;

public class Question {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.id
     *
     * @mbg.generated Sun May 20 22:57:24 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.title
     *
     * @mbg.generated Sun May 20 22:57:24 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.desription
     *
     * @mbg.generated Sun May 20 22:57:24 CST 2018
     */
    private String desription;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.id
     *
     * @return the value of question.id
     *
     * @mbg.generated Sun May 20 22:57:24 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.id
     *
     * @param id the value for question.id
     *
     * @mbg.generated Sun May 20 22:57:24 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.title
     *
     * @return the value of question.title
     *
     * @mbg.generated Sun May 20 22:57:24 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.title
     *
     * @param title the value for question.title
     *
     * @mbg.generated Sun May 20 22:57:24 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.desription
     *
     * @return the value of question.desription
     *
     * @mbg.generated Sun May 20 22:57:24 CST 2018
     */
    public String getDesription() {
        return desription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.desription
     *
     * @param desription the value for question.desription
     *
     * @mbg.generated Sun May 20 22:57:24 CST 2018
     */
    public void setDesription(String desription) {
        this.desription = desription == null ? null : desription.trim();
    }
}